name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with java
      run: mkdir classes ; javac -d classes src/*.java; ls classes
    - name: prepare artifacts data
      run: cp -r src/Data classes; ls classes
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with: 
        name: CarteMaroc
        path: classes

